---
  - name: Verify
    hosts: all
    gather_facts: false
    tasks:
      - name: "dnsmasq - check package status"
        package:
          name: "dnsmasq"
        check_mode: yes
        register: pkg_status

      - debug: 
          var: pkg_status

      - name: "dnsmasq - test package is installed"
        assert:
          that:
            - pkg_status.present